config/routes.rb
Rails.application.routes.draw do
  get 'charges/create', as:'charges'

  get 'customers/form'

  get 'stores/form', as: 'form'

  get 'stores/index', as: 'stores'

  post 'stores', to: 'pages#stores'

  post 'stores/search', to: 'stores#search'

  get 'stores/:store_id', to: 'stores#show', as: 'store'
  get 'pages/home'
  get 'authors/index'
  get 'books/index'


  get '/books/:book_id', to: 'books#show', as: 'book'

  root to: 'pages#home'
  get 'home', to: 'pages#home', as: 'home'
  get 'books', to: 'books#index', as: 'books'
  get 'authors', to: 'authors#index', as: 'authors'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  scope(:book_name, -> (b_name) { where("LOWER(title) like ?", "%#{b_name}%") })

  scope(:author_name, ->(a_name) {includes(:author).references(:author).where("LOWER(authors.name) like ?", "%#{a_name}%") })

end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :full_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def full_address
    return "#{address}, #{city}, #{state}, #{postcode}, #{country}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(rating: :desc)
    filter_params.each do |key, value|
      @books = @books.public_send(key, value) if value.present?
    end
  end
  def show
    @book = Book.find(params[:book_id])
  end

  private

  def filter_params
  params.slice(:book_name, :author_name)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_item
  def new

  end

  def create
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source => params[:stripeToken]
    )

  charge = Stripe::Charge.create(
    :customer => customer.id,
    :amount => (@book.price * 100).to_i, # in cents
    :description => 'Rails Stripe Customer',
    :currency => 'aud'
    )
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private
  def set_item
    @book = Book.find(params[:book_id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def form
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all

    # if params[:address]
    #   @nearest_stores = Store.near(params[:address], 50, units: 'km')[0]
    # end


  end

  def show
    @store = Store.find(params[:store_id])
  end

  def search
    @search = Store.near(params[:address])[0]
  rescue
  flash[:notice] = 'There was an error entering that address'
  redirect_to(:action => 'index')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<%= link_to 'Back', home_path, class: "btn btn-info" %>

<% @authors.each do |author| %>
  <h2><%= author.name %></h2>
  <p>Bio: <%= author.bio %></p>
  <p>List of Books:</p>
  <ul>
  <% author.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
  </ul>


<% end %>

app/views/books/index.html.erb
<style>

  .box {
    display: flex;
    padding-left: 10px;
    margin: 5px;
  }
  .box2 {

    display: flex;
    flex-wrap: wrap;
  }

</style>


<h1>Books</h1>
<%= link_to 'Back', home_path, class: "btn btn-info" %>
<br>
<br>

<div class="panel panel-default">
  <div class="panel-body">
    <form class="form-inline">
      <div class="form-group">
        <label for="book_name">&nbsp;&nbsp;Title:&nbsp;&nbsp;&nbsp;</label>
        <input type="text" name="book_name"  class="form-control">
      </div>

      <div class="form-group">
        <label for="author_name">&nbsp;&nbsp;Author:&nbsp;&nbsp;&nbsp;</label>
        <input type="text" name="author_name"  class="form-control">
      </div>

      &nbsp;&nbsp;
      <input type="submit" value="Filter" class="btn btn-outline-success">
      &nbsp;&nbsp;
      <%= link_to 'Clear Filters', books_path, class: "btn btn-outline-danger" %>
    </form>
  </div>
</div>

<br>

<% @books.each do |book| %>
  <div class='box'>
    <%= link_to (image_tag(book.img, options={ height: "100px", width: "70px"})), book %>
    <div class'box2'>
      <h2><%= link_to book.title, book_path(book) %></h2>
      <p>Written By: <%= book.author.name %> | Rating: <%= pluralize(book.rating, 'Star') %> | Summary: <%= book.summary %></p>
    </div>
  </div>

<% end %>

app/views/books/show.html.erb
<style>
  .showbook {
    text-align: center;
  }

</style>
<div class="showbook">
<h1><%= @book.title %></h1>

&nbsp;&nbsp;&nbsp;<%= image_tag(@book.img, options={ height: "300px"}) %>

<h3>Written by: <%= @book.author.name %></h3>

<h4>Summary:</h4>

<p><%= @book.summary %></p>

<h4>Price: <%= number_to_currency(@book.price) %></h4>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

  </article>

  <%= hidden_field_tag :book_id, @book.id %>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

<br>
<%= link_to 'Back', books_path, class: "btn btn-info"%>
</div>

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/customers/form.html.erb
<h1>Customers</h1>

<%= form_for customer_form_path do |form| %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :postcode %>
    <%= form.text_field :postcode %>
  </div>

  <div>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.submit "Submit" %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazin: Books Books Books</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Amazin</h1>

<h3><%= link_to 'Books',books_path, class: "btn btn-info"  %> | <%= link_to 'Authors',authors_path, class: "btn btn-info"  %> | <%= link_to 'Stores', stores_path, class: "btn btn-info" %></h3>

app/views/stores/index.html.erb
<h1>Stores</h1>
<p><%= link_to 'Back', home_path, class: "btn btn-info" %>

<% @stores.each do |store| %>

  <h3><%= link_to store.title, store_path(store) %></h3>
  <p>Address: <%= store.full_address %></p>

<% end %>


<p id="notice"><strong><%= notice %></strong></p>

<%= form_tag("/stores/search", method: "post") do %>
  <%= label_tag(:address, "Enter your address:") %>
  <%= text_field_tag(:address) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/stores/search.html.erb
<h1><%= @search.title %></h1>
<h3>Address: <%= @search.full_address %></h3>
<p>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCuEtLjJSQSbK5lUfK91fiuOUht2NOeGck
    &q=<%= @search.full_address %>" allowfullscreen>
</iframe>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/streetview?key=AIzaSyCuEtLjJSQSbK5lUfK91fiuOUht2NOeGck
  &location=<%= @search.latitude %>,<%= @search.longitude %>
  &heading=210
  &pitch=10
  &fov=35" allowfullscreen>
</iframe>
</p>

<p><%= link_to 'Back', stores_path, class: "btn btn-info" %></p>

app/views/stores/show.html.erb
<h2><%= @store.title %></h2>
<h3>Address: <%= @store.full_address %></h3>
<p>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCuEtLjJSQSbK5lUfK91fiuOUht2NOeGck
    &q=<%= @store.full_address %>" allowfullscreen>
</iframe>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/streetview?key=AIzaSyCuEtLjJSQSbK5lUfK91fiuOUht2NOeGck
  &location=<%= @store.latitude %>,<%= @store.longitude %>
  &heading=210
  &pitch=10
  &fov=35" allowfullscreen>
</iframe>
</p>

<p><%= link_to 'Back', stores_path, class: "btn btn-info" %></p>